/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.vass.liferay.servicebuilder.libro.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.vass.liferay.servicebuilder.libro.model.Libro;
import com.vass.liferay.servicebuilder.libro.model.LibroModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the Libro service. Represents a row in the &quot;LIBRO_Libro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>LibroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LibroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LibroImpl
 * @generated
 */
@ProviderType
public class LibroModelImpl extends BaseModelImpl<Libro> implements LibroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a libro model instance should use the <code>Libro</code> interface instead.
	 */
	public static final String TABLE_NAME = "LIBRO_Libro";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"libroId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"titulo", Types.VARCHAR}, {"publicacion", Types.TIMESTAMP},
		{"genero", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("libroId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("titulo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("publicacion", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("genero", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LIBRO_Libro (uuid_ VARCHAR(75) null,libroId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,titulo VARCHAR(75) null,publicacion DATE null,genero VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table LIBRO_Libro";

	public static final String ORDER_BY_JPQL = " ORDER BY libro.titulo ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LIBRO_Libro.titulo ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long GROUPID_COLUMN_BITMASK = 2L;

	public static final long TITULO_COLUMN_BITMASK = 4L;

	public static final long UUID_COLUMN_BITMASK = 8L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public static final String MAPPING_TABLE_LIBRO_LIBROS_ESCRITORES_NAME =
		"LIBRO_Libros_Escritores";

	public static final Object[][]
		MAPPING_TABLE_LIBRO_LIBROS_ESCRITORES_COLUMNS = {
			{"companyId", Types.BIGINT}, {"escritorId", Types.BIGINT},
			{"libroId", Types.BIGINT}
		};

	public static final String
		MAPPING_TABLE_LIBRO_LIBROS_ESCRITORES_SQL_CREATE =
			"create table LIBRO_Libros_Escritores (companyId LONG not null,escritorId LONG not null,libroId LONG not null,primary key (escritorId, libroId))";

	public LibroModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _libroId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLibroId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _libroId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Libro.class;
	}

	@Override
	public String getModelClassName() {
		return Libro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Libro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Libro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Libro, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Libro)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Libro, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Libro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Libro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Libro, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Libro, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Libro>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Libro.class.getClassLoader(), Libro.class, ModelWrapper.class);

		try {
			Constructor<Libro> constructor =
				(Constructor<Libro>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Libro, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Libro, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Libro, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Libro, Object>>();
		Map<String, BiConsumer<Libro, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Libro, ?>>();

		attributeGetterFunctions.put("uuid", Libro::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Libro, String>)Libro::setUuid);
		attributeGetterFunctions.put("libroId", Libro::getLibroId);
		attributeSetterBiConsumers.put(
			"libroId", (BiConsumer<Libro, Long>)Libro::setLibroId);
		attributeGetterFunctions.put("groupId", Libro::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Libro, Long>)Libro::setGroupId);
		attributeGetterFunctions.put("companyId", Libro::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Libro, Long>)Libro::setCompanyId);
		attributeGetterFunctions.put("userId", Libro::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Libro, Long>)Libro::setUserId);
		attributeGetterFunctions.put("userName", Libro::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Libro, String>)Libro::setUserName);
		attributeGetterFunctions.put("createDate", Libro::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Libro, Date>)Libro::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Libro::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Libro, Date>)Libro::setModifiedDate);
		attributeGetterFunctions.put("titulo", Libro::getTitulo);
		attributeSetterBiConsumers.put(
			"titulo", (BiConsumer<Libro, String>)Libro::setTitulo);
		attributeGetterFunctions.put("publicacion", Libro::getPublicacion);
		attributeSetterBiConsumers.put(
			"publicacion", (BiConsumer<Libro, Date>)Libro::setPublicacion);
		attributeGetterFunctions.put("genero", Libro::getGenero);
		attributeSetterBiConsumers.put(
			"genero", (BiConsumer<Libro, String>)Libro::setGenero);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getLibroId() {
		return _libroId;
	}

	@Override
	public void setLibroId(long libroId) {
		_libroId = libroId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTitulo() {
		if (_titulo == null) {
			return "";
		}
		else {
			return _titulo;
		}
	}

	@Override
	public void setTitulo(String titulo) {
		_columnBitmask = -1L;

		if (_originalTitulo == null) {
			_originalTitulo = _titulo;
		}

		_titulo = titulo;
	}

	public String getOriginalTitulo() {
		return GetterUtil.getString(_originalTitulo);
	}

	@Override
	public Date getPublicacion() {
		return _publicacion;
	}

	@Override
	public void setPublicacion(Date publicacion) {
		_publicacion = publicacion;
	}

	@Override
	public String getGenero() {
		if (_genero == null) {
			return "";
		}
		else {
			return _genero;
		}
	}

	@Override
	public void setGenero(String genero) {
		_genero = genero;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Libro.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Libro.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Libro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Libro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LibroImpl libroImpl = new LibroImpl();

		libroImpl.setUuid(getUuid());
		libroImpl.setLibroId(getLibroId());
		libroImpl.setGroupId(getGroupId());
		libroImpl.setCompanyId(getCompanyId());
		libroImpl.setUserId(getUserId());
		libroImpl.setUserName(getUserName());
		libroImpl.setCreateDate(getCreateDate());
		libroImpl.setModifiedDate(getModifiedDate());
		libroImpl.setTitulo(getTitulo());
		libroImpl.setPublicacion(getPublicacion());
		libroImpl.setGenero(getGenero());

		libroImpl.resetOriginalValues();

		return libroImpl;
	}

	@Override
	public int compareTo(Libro libro) {
		int value = 0;

		value = getTitulo().compareTo(libro.getTitulo());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Libro)) {
			return false;
		}

		Libro libro = (Libro)obj;

		long primaryKey = libro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		LibroModelImpl libroModelImpl = this;

		libroModelImpl._originalUuid = libroModelImpl._uuid;

		libroModelImpl._originalGroupId = libroModelImpl._groupId;

		libroModelImpl._setOriginalGroupId = false;

		libroModelImpl._originalCompanyId = libroModelImpl._companyId;

		libroModelImpl._setOriginalCompanyId = false;

		libroModelImpl._setModifiedDate = false;

		libroModelImpl._originalTitulo = libroModelImpl._titulo;

		libroModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Libro> toCacheModel() {
		LibroCacheModel libroCacheModel = new LibroCacheModel();

		libroCacheModel.uuid = getUuid();

		String uuid = libroCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			libroCacheModel.uuid = null;
		}

		libroCacheModel.libroId = getLibroId();

		libroCacheModel.groupId = getGroupId();

		libroCacheModel.companyId = getCompanyId();

		libroCacheModel.userId = getUserId();

		libroCacheModel.userName = getUserName();

		String userName = libroCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			libroCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			libroCacheModel.createDate = createDate.getTime();
		}
		else {
			libroCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			libroCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			libroCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		libroCacheModel.titulo = getTitulo();

		String titulo = libroCacheModel.titulo;

		if ((titulo != null) && (titulo.length() == 0)) {
			libroCacheModel.titulo = null;
		}

		Date publicacion = getPublicacion();

		if (publicacion != null) {
			libroCacheModel.publicacion = publicacion.getTime();
		}
		else {
			libroCacheModel.publicacion = Long.MIN_VALUE;
		}

		libroCacheModel.genero = getGenero();

		String genero = libroCacheModel.genero;

		if ((genero != null) && (genero.length() == 0)) {
			libroCacheModel.genero = null;
		}

		return libroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Libro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Libro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Libro, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Libro)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Libro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Libro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Libro, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Libro)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Libro>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _libroId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _titulo;
	private String _originalTitulo;
	private Date _publicacion;
	private String _genero;
	private long _columnBitmask;
	private Libro _escapedModel;

}